[Settings]

[build]
  publish = "deploy"
  command = "npm run full"

[context.deploy-preview]
  publish = "dist"
  command = "npm run generate"

[context.branch-deploy]
  publish = "dist"
  command = "npm run generate"
